#!/bin/bash
set -e

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
BAZEL_PROFILE_PATH=""
BAZEL_PROFILE_NAME=""

__upload_gh_profile() {
  local GITHUB_JOB="${GITHUB_JOB:-}"
  local ENV_PATH="/tmp/${GITHUB_JOB}.action_env.sh" 
  [[ -e "${ENV_PATH}" ]] || return
  source ${ENV_PATH}
  export INPUT_NAME=$GITHUB_JOB.$BAZEL_PROFILE_NAME
  export INPUT_PATH=$BAZEL_PROFILE_PATH
  export INPUT_RETENTIONDAYS=90
  node $BAZEL_PROFILE_ROOT/upload-artifact/index.js
}

__bazel_exit_trap() {
  __upload_gh_profile
}

trap __bazel_exit_trap EXIT

__bazel_main() {
  # Bazel next to this file
  local CMD_NAME="$(basename $0)"
  local CMD="${SCRIPTPATH}/$CMD_NAME.og"

  if [[ ! -e $CMD ]]; then
    echo "[WARN] Missing $CMD_NAME"
    CMD=$(which $CMD_NAME)
  fi

  BAZEL_PROFILE_NAME=bazel-profiles-"$(date +"%s")"
  export BAZEL_PROFILE_PATH=/tmp/$BAZEL_PROFILE_NAME

  local ARGS=("${CMD}")
  local PARSE_PROFILE=0
  local ADDED=0
  for ARG in "$@"; do
    if [[ "$ARG" =~ --profile= ]]; then
      continue
    elif [[ "$ARG" =~ --profile ]]; then
      PARSE_PROFILE=1
      continue
    elif [[ $PARSE_PROFILE -eq 1 ]]; then
      PARSE_PROFILE=0
      continue
    elif [[ $ADDED -eq 0 ]] && [[ $ARG == "--" ]]; then
      ARGS+=("--profile=$BAZEL_PROFILE_PATH")
      ADDED=1
    fi

    ARGS+=("${ARG}")
  done

  if [[ $ADDED -eq 0 ]]; then 
    ARGS+=("--profile=$BAZEL_PROFILE_PATH")
  fi
  (exec "${ARGS[@]}")
}

__bazel_main "$@"
